### ISSUE TITLE
Throw 403 status code?

### ISSUE THREAD

**Issue by matternow** [sjelfull/craft3-restrict#5]
https://github.com/sjelfull/craft3-restrict/blob/1268ae2b8eb8a005ac6a6ccc0cfa62cda289cc6c/src/services/RestrictService.php#L74

It feels like a site administrator should be able to throw a 403 error rather than just do a 302 redirect over to a normal page. Would you be interested in a pull request for this? Thought would be that out of the box it would work as it does now (to maintain backwards compatibility), but if they set a config bool of `throw403` or something like that, then we could throw a normal 403 exception that can be handled by 403.twig / error.twig, etc.

**Comment by jamesmacwhite** [comment]
As an alternative you could create a template that throws the 403 code with exit and point restrict to that.

I have found that depending on a projects templates, the template option might not work when loading certain extended templates that use plugins like asset rev, because it seems not everything is fully loaded when restrict calls it. I use the above workaround to redirect to a /restricted URI which loads the 403 error template configured. It doesn't work however when I specify that template directly.

**Comment by sjelfull** [comment]
@jamesmacwhite There might be a race condition because not all plugins might not be loaded at the time it runs its checks at the moment.

There is the `Plugins::EVENT_AFTER_LOAD_PLUGINS` event which might fix this. Feel free to take a stab at a PR if you have time. [Here is an example of how its used](https://github.com/nystudio107/craft-seomatic/blob/v3/src/Seomatic.php#L451-L466).

@matternow As for the 403 error, I believe @jamesmacwhite latest change fixes this (as long as you haven't set a redirect url). I'll tag a release in a sec.
